apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
  creationTimestamp: null
  labels:
    app: tsf-mysql
    chart: tsf-mysql-6.8.0
    component: master
    heritage: Tiller
    release: tsf-mysql
  name: tsf-mysql-master-np
  selfLink: /api/v1/namespaces/default/services/tsf-mysql
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    nodePort: 31306
    port: 3306
    protocol: TCP
    targetPort: mysql
  - name: metrics
    nodePort: 31307
    port: 9104
    protocol: TCP
    targetPort: metrics
  selector:
    app: tsf-mysql
    component: master
    release: tsf-mysql
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
