global:
  host: null
  replicas: 1
  registry:
    address: index.alauda.cn
  images:
    alarm:
      repository: tsf/tsf-alarm
      tag: v1.0
  namespace: alauda-system
  node_list:
    one: 1.1.1.1
    two: 2.2.2.2
    three: 3.3.3.3
  volumes_root_hostpath:
    name: tsf-root
    hostPath:
      path: /root/tsf/
      type: ""
  volumes_data_hostpath:
    name: tsf-data
    hostPath:
      path: /data/
      type: ""
  volumes_alarm_pvc:

  alarm:
    resources: |
      requests:
        cpu: "2048m"
        memory: "2048Mi"
      limits:
        cpu: "4096m"
        memory: "8192Mi"


