# Default values for license-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  node_list:
    TSF_NODE1: 10.0.129.13 
    TSF_NODE2: 10.0.129.20
    TSF_NODE3: 10.0.128.30
  volumes_root_hostpath:
    name: tsf-root
    hostPath:
      path: /root/tsf/
      type: ""
  volumes_data_hostpath:
    name: tsf-data
    hostPath:
      path: /data/
      type: ""
  volumes_fscgroup_hostpath:
    name: fscgroup
    hostPath:
      path: /sys/fs/cgroup
      type: ""


