apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: cluster.local/bsma-nfs-storageclass-nfs-client-provisioner
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mysql
    component: slave
    release: mysql-ga
  name: data-mysql-ga-slave-0
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/data-mysql-ga-slave-0
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: pvc-2d91e62f-46fb-11ea-9fc8-525400feee69
status: {}
