apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: haproxy
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: haproxy
    spec:
      nodeSelector:
        tsf.product.alauda.io/tsf-node1: enabled
      hostNetwork: true
      containers:
      - image: index.alauda.cn/alaudaorg/haproxy:v6tcp3306
        env:
        - name: MYSQL_MASTER_SVC_IP
          value: "10.97.83.223"
        name: haproxy
        resources: {}
status: {}
